services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - ispnet

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: portal
    networks:
      - ispnet

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    depends_on:
      - portal
      - webmail
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - ispnet
    command: [sh, -c, "nginx -g 'daemon off;' & while :; do sleep 6h; nginx -s reload; done"]

  mail:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.asa.br
    restart: always
    tty: true
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
    networks:
      - ispnet

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    depends_on:
      - mail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail
      - ROUNDCUBEMAIL_SMTP_SERVER=mail
    ports:
      - "8081:80/tcp"
    networks:
      - ispnet

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # Comando otimizado para renovação
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew -q; done'"

networks:
  ispnet:
    driver: bridge
