services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: portal
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
  mail:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.asa.br #? (acho que tem que mudar isso)
    restart: always
    tty: true
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
